// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIzFAThgvaSf8t4z3xB55Eh-b8gra97rM',
    appId: '1:452231569768:android:6af06f15915081f18fb6dd',
    messagingSenderId: '452231569768',
    projectId: 'saral-office',
    storageBucket: 'saral-office.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6wNPY5Hrmc6rraS1FFid4bK-zEDLW7d8',
    appId: '1:452231569768:ios:1d9d77f200dce7c68fb6dd',
    messagingSenderId: '452231569768',
    projectId: 'saral-office',
    storageBucket: 'saral-office.firebasestorage.app',
    iosBundleId: 'com.example.saralOffice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN-Ik3gZPmHa35dxY4tZZqEJjmMIEyx0Q',
    appId: '1:452231569768:web:3353e1d3898a3fe58fb6dd',
    messagingSenderId: '452231569768',
    projectId: 'saral-office',
    authDomain: 'saral-office.firebaseapp.com',
    storageBucket: 'saral-office.firebasestorage.app',
  );
}
